swagger: "2.0"
info:
  description: "This is a simple API documentation by Thanh Tung Nguyen."
  version: "1.0.0"
  title: "Job Application"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "tttnguyen.sport@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
- name: "job_application"
  description: "Everything about your job applications"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /api/job_applications:
    get:
      tags:
      - "pet"
      summary: "Get all job applications"
      description: "Every job applications is listed at this end"
      operationId: "findPetsByStatus"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/job_application"
        "400":
          description: "Invalid status value"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  job_application:
    type: "object"
    properties:
      companyName:
        type: "string"
      jobTitle:
        type: "string"
      applicationDate:
        type: "string"
        format: "date-time"
      applicationStatus:
        type: "string"
        description: "Application Status"
        enum:
        - "applied"
        - "received phone call"
        - "waiting for general interview"
        - "waiting for technical interview"
        - "hired"
      salary:
        type: "integer"
        format: "int64"
      offer:
        type: "boolean"
        default: false
    xml:
      name: "Order"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"